KER-363
City-of-Helsinki/kerrokantasi-ui pull request #1038
Opened 2024-06-17 08:12 UTC by arpargo

Upgrade all of the deprecated libraries.

2024-06-19 10:44 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-06-19 11:26 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-06-19 11:35 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-06-24 09:48 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-06-24 09:57 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-06-24 10:51 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-06-24 11:00 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-06-25 07:43 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-06-25 07:52 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-06-25 08:27 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-06-25 09:08 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-06-25 09:16 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-06-25 09:50 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-06-25 09:58 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-06-25 12:32 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-06-25 12:41 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-06-25 12:53 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-06-25 13:01 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-07-04 08:05 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-07-04 08:16 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-07-05 09:54 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-07-05 10:04 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-08-01 09:47 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-08-01 09:57 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-08-01 10:55 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-08-01 11:06 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-08-01 12:36 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-08-01 12:46 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-08-05 09:57 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-08-05 10:08 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-08-05 10:47 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-08-05 10:58 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-08-12 12:10 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-08-12 12:21 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-08-13 12:29 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-08-16 10:44 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-08-16 10:53 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-08-16 11:32 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-08-16 11:41 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-08-19 13:16 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-08-19 13:22 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-08-28 10:01 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-08-28 10:05 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-08-30 10:03 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-08-30 10:07 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-09-03 10:47 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-09-03 10:52 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-09-04 11:42 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-09-04 12:19 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-09-04 12:24 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-09-06 10:50 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-09-06 10:55 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-09-11 08:38 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-09-11 08:42 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-09-11 09:27 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-09-11 09:31 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-09-11 09:53 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-09-11 10:10 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-09-11 10:15 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-09-11 10:51 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-09-11 10:55 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-09-11 11:15 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-09-11 11:33 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-09-11 11:37 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-09-11 12:06 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-09-11 12:20 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-09-11 12:57 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-09-11 13:19 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-09-12 06:49 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-09-12 06:54 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-09-12 07:33 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-09-12 07:39 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-09-12 08:00 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-09-12 09:54 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-09-12 10:17 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-09-12 10:22 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-09-12 11:13 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-09-12 12:38 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-09-12 12:41 UTC, terovirtanen commented
## e2e tests result is __success__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :laughing::tada::tada::tada:

2024-09-13 07:38 UTC, mikkojamG commented on src/createStore.js
> +
Commented code should be removed 👀

2024-09-13 07:38 UTC, mikkojamG commented on src/views/Hearings/index.jsx
> +  // location: PropTypes.shape({
Commented code should be removed 👀

2024-09-13 08:04 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-09-13 08:05 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-09-13 08:09 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-10-07 10:44 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-10-07 10:48 UTC, terovirtanen commented
## e2e tests result is __success__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :laughing::tada::tada::tada:

2024-10-08 08:53 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-10-08 08:57 UTC, terovirtanen commented
## e2e tests result is __success__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :laughing::tada::tada::tada:

2024-10-18 09:15 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-10-18 09:19 UTC, terovirtanen commented
## e2e tests result is __success__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :laughing::tada::tada::tada:

2024-10-18 10:03 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-10-18 10:08 UTC, terovirtanen commented
## e2e tests result is __success__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :laughing::tada::tada::tada:

2024-10-21 07:58 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-10-21 08:03 UTC, terovirtanen commented
## e2e tests result is __success__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :laughing::tada::tada::tada:

2024-10-22 08:27 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-10-22 08:32 UTC, terovirtanen commented
## e2e tests result is __success__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :laughing::tada::tada::tada:

2024-10-28 08:59 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-10-28 09:04 UTC, terovirtanen commented
## e2e tests result is __success__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :laughing::tada::tada::tada:

2024-10-28 10:31 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-10-28 10:33 UTC, mikkojamG requested changes

2024-10-28 10:33 UTC, mikkojamG commented on src/components/Hearing/Comment/index.jsx
> +  const isAdminUser = () => typeof props.data.organization === 'string' || Array.isArray(props.data.organization);
Probably could just use isAdmin util function instead 🤔

2024-10-28 10:33 UTC, mikkojamG commented on src/components/admin/HearingFormStep1.jsx
> +              /*
Commented code should be removed 👀

2024-10-28 10:45 UTC, terovirtanen commented
## e2e tests result is __success__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :laughing::tada::tada::tada:

2024-10-28 10:58 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-10-28 11:12 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-10-28 11:17 UTC, terovirtanen commented
## e2e tests result is __success__ for https://kerrokantasi-pr1038-ui.dev.hel.ninja :laughing::tada::tada::tada:

2024-10-28 11:35 UTC, mikkojamG approved these changes
🎉

2024-10-28 11:46 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1038-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-10-28 12:06 UTC, merged