[DRAFT] KER-376 Sentry fixes
City-of-Helsinki/kerrokantasi-ui pull request #1043
Opened 2024-08-05 11:10 UTC by mikkojamG

# Otsikko 1 - PR:n otsikko

## Otsikko 2 - Selitys mitä tapahtuu PR:ssä

### Mitä sisältää (Esim. mitä projektinhallinnan tehtäväkortteja käsittelee)

-----------------------------------------------------------------------------------------------
### Breakdown:

#### Kategoria-otsikko
 1. Tiedosto 
     * Selitys muutoksista
   
 2. Tiedosto
     * Selitys muutoksista
    
 3. Tiedosto
     * Selitys muutoksista
     
#### Kategoria-otsikko
 1. Tiedosto 
     * Selitys muutoksista
   
 2. Tiedosto
     * Selitys muutoksista
    
 3. Tiedosto
      * Selitys muutoksista

2024-08-05 11:21 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1043-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-08-05 11:25 UTC, terovirtanen commented
## e2e tests result is __success__ for https://kerrokantasi-pr1043-ui.dev.hel.ninja :laughing::tada::tada::tada:

2024-08-06 05:12 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1043-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-08-06 05:16 UTC, terovirtanen commented
## e2e tests result is __success__ for https://kerrokantasi-pr1043-ui.dev.hel.ninja :laughing::tada::tada::tada:

2024-08-06 07:10 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1043-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-08-06 07:15 UTC, terovirtanen commented
## e2e tests result is __success__ for https://kerrokantasi-pr1043-ui.dev.hel.ninja :laughing::tada::tada::tada:

2024-08-06 08:38 UTC, arpargo requested changes

2024-08-06 08:38 UTC, arpargo commented on src/index.js
> +      dsn: config.uiConfig.sentryDns,
Typo?

2024-08-06 08:45 UTC, mikkojamG commented on src/index.js
> +      dsn: config.uiConfig.sentryDns,
Fixed'dd.

2024-08-06 08:46 UTC, arpargo approved these changes

2024-08-06 08:58 UTC, terovirtanen commented
**KERROKANTASI-UI branch is deployed to platta: https://kerrokantasi-pr1043-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-08-06 09:02 UTC, terovirtanen commented
## e2e tests result is __success__ for https://kerrokantasi-pr1043-ui.dev.hel.ninja :laughing::tada::tada::tada:

2024-08-06 09:03 UTC, merged